language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: "cbbb2873-85de-4e02-b21b-528381c26b06"
  app: valeriano-system-15107